### ISSUE TITLE
Injected style in preview and view mode targets all a instead of #embedOverlay a

### ISSUE THREAD

**Issue by kikohs** [cables-gl/cables_docs#651]
In the view mode this style is injected

```css
 #embedOverlay a, a:hover, a:focus, a:active {text-decoration: none;color: inherit;display: block;height: 100%;width: 100%;}
```

It should be 

```css
 #embedOverlay a,  #embedOverlay  a:hover,  #embedOverlay  a:focus, #embedOverlay  a:active {text-decoration: none;color: inherit;display: block;height: 100%;width: 100%;}
```

Otherwise all `a:hover a:focus a:active` are targetted and make it quite difficult to fix from the editor.

Thanks!
